#                             # NUMPY TUTORIAL  -( by Muhsin ) 

In [2]:
import numpy as np
x = np.array([1,2,3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


how to create numpy array and checking the type

In [3]:
%timeit [j**4 for j in range(1,9)]

4.41 µs ± 42.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
import numpy as np
%timeit np.arange(1,9)**4

2.96 µs ± 136 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


checking the speed between lists and numpy

In [6]:
import numpy as np
x = [1,2,3,4]

y = np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
l =[]

for i in range(1,6):
    
    int_1 = int(input('enter the number :'))
    l.append(int_1)
    
print(np.array(l))    

enter the number :1
enter the number :2
enter the number :3
enter the number :5
enter the number :5
[1 2 3 5 5]


# Dimensions in Arrays

# 1-D Arrays --- [1,2,3,4]



#  2-D Arrays ---[ [1,2,3,4] ]

#  3-D Arrays --- [[[1,2,3,4]]]

In [10]:
ar2 = np.array([[1,2,3]])
print(ar2)
print(ar2.ndim)

[[1 2 3]]
2


n.dim ---- for checking the dimensions

In [12]:
ar3 = np.array([[[1,2,3]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]]]
3


# Arrays filled with 0's

In [14]:
import numpy as np

ar_zero = np.zeros(4)

ar_zero1 = np.zeros((3,4))

print(ar_zero1)
print()
print(ar_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0. 0. 0. 0.]


# Arrays filled with 1's

In [15]:
ar = np.ones(4)
print(ar)

[1. 1. 1. 1.]


# Create an empty array

In [17]:
ar = np.empty(4)
print(ar)

[1. 1. 1. 1.]


# An array with a range of elements

In [18]:
ar = np.arange(5)
print(ar)

[0 1 2 3 4]


# Array diagonal element filled with 1's

In [19]:
ar= np.eye(3,3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# linspace

In [20]:
ar = np.linspace(0,10,num=6)
print(ar)

[ 0.  2.  4.  6.  8. 10.]


# Create NumPy Arrays with Random Numbers

# rand() :   the function is used to generate a random value between 0 to 1.

In [1]:
import numpy as np

ar = np.random.rand(6)
print(ar)

[0.32766204 0.17859158 0.41634251 0.15512281 0.359636   0.44995542]


In [2]:
ar2 = np.random.rand(3,4)
print(ar2)

[[0.07763672 0.17278224 0.50952978 0.11927982]
 [0.97802016 0.66275342 0.23364009 0.79477493]
 [0.2149018  0.93378504 0.34641823 0.26349285]]


# randn():    the function is used to generate a random value close to zero.This may return positive or negative numbers as well.

In [3]:
ar3 = np.random.randn(4)
print(ar3)

[ 0.69853427 -0.75477476 -1.14210786 -0.72278169]


# ranf( ) : the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the happen interval [0.0, 1.0).

In [4]:
ar4 = np.random.ranf(4)
print(ar4)

[0.1669314  0.46015752 0.7735384  0.60275559]


# randint(min,max,total values ) : the fuction is used to generate a random number between a given range

In [8]:
ar5 = np.random.randint(1,6,4)

print(ar5)

[3 5 3 4]


# Data Types in Numpy

In [12]:
varr = np.array([1,2,3,4])

print('data type : ' ,varr.dtype)

data type :  int32


.dtype used to see the data type

In [13]:
varrr = np.array([2.3,4.6,8.4])

print('data type : ' ,varrr.dtype)

data type :  float64


In [14]:
varr = np.array(['muhsin','bashir'])

print('data type : ' ,varr.dtype)

data type :  <U6


In [17]:
va = np.array([1,2,3,4,'muhsin'])

print('data type : ' ,va.dtype)

data type :  <U11


# CONVERTING DATA TYPES

In [20]:
x = np.array([1,2,3,4],dtype = np.int8)

print('Data Type :',x.dtype)

Data Type : int8


In [23]:
x1 = np.array([1,2,3,4],dtype = "f")

print('Data Type :',x1.dtype)
print(x1)

Data Type : float32
[1. 2. 3. 4.]


In [26]:
x2 = np.array([2,3,4,5])

new = np.float32(x2)

print('Data Type: ',x2.dtype)
print(x2)
print(new)

Data Type:  int32
[2 3 4 5]
[2. 3. 4. 5.]


DIRECT CONVERSION WITH .astype

In [27]:
x4 = np.array([4,45,6])

neww = x4.astype(float)
print(x4)
print(neww)

[ 4 45  6]
[ 4. 45.  6.]


# ARITHMETIC OPERATIONS IN NUMPY ARRAYS

In [28]:
var = np.array([1,2,3,4])

varadd = var + 3

print(varadd)

[4 5 6 7]


In [29]:
var = np.array([1,2,3,4])

varadd = var - 3

print(varadd)

[-2 -1  0  1]


In [30]:
var = np.array([1,2,3,4])

varadd = var * 3

print(varadd)

[ 3  6  9 12]


In [31]:
var = np.array([1,2,3,4])

varadd = var / 3

print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [32]:
var = np.array([1,2,3,4])

varadd = var % 3

print(varadd)

[1 2 0 1]


In [34]:
varr1 = np.array([1,2,3,4])

varr2 = np.array([1,2,3,4])

varadd = np.add(varr1,varr2)

print(varadd)

[2 4 6 8]


In [42]:
varr5 = np.array([1,2,3,4])

varadd = np.reciprocal(varr5)

print(varadd)

[1 0 0 0]


# 2-D ARRAY

In [41]:
var12 = np.array([[1,2,3],[1,2,3]])

var13 = np.array([[1,2,3],[1,2,3]])

varadd12 = var12 + var13

print(var12)
print(var13)
print()
print(varadd12)

[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]]

[[2 4 6]
 [2 4 6]]


# Arithmetic Functions

In [52]:
z = np.array([4,3,4,6,7,8,5])

print("min",np.min(z),'position',np.argmin(z))
print('max',np.max(z),'position',np.argmax(z))
print('sqrt',np.sqrt(z))

min 3 position 1
max 8 position 5
sqrt [2.         1.73205081 2.         2.44948974 2.64575131 2.82842712
 2.23606798]


.argmin for position of the element

In [50]:
v = np.array([[1,2,3,4],[4,5,6,7]])
print(np.min(v,axis=1))

[1 4]


axis =0 === cloumn
axis =1 === row


In [56]:
z1 = np.array([90,120,60])

print('sin',np.sin(z1))
print('cos',np.cos(z1))
print('cumsum',np.cumsum(z1))


sin [ 0.89399666  0.58061118 -0.30481062]
cos [-0.44807362  0.81418097 -0.95241298]
cumsum [ 90 210 270]


# Shape in NumPy Arrays 

In [60]:
m = np.array([1,2,3,4,5], ndmin = 4)

print(m)
print(m.ndim)
print(m.shape)

[[[[1 2 3 4 5]]]]
4
(1, 1, 1, 5)


.ndmin ==== for giving dimensions

# Reshaping in NumPy Arrays

In [64]:
vv= np.array([5,6,7,89,4,3])

x= vv.reshape(3,2)
print(x)
print(x.ndim)

[[ 5  6]
 [ 7 89]
 [ 4  3]]
2


In [72]:
vvv= np.array([5,6,7,9,4,3,7,4,9,10,11,12])

xv= vvv.reshape(2,3,2)
print(xv)
print(xv.ndim)

[[[ 5  6]
  [ 7  9]
  [ 4  3]]

 [[ 7  4]
  [ 9 10]
  [11 12]]]
3


In [74]:
vvv= np.array([5,6,7,9,4,3,7,4,9,10,11,12])

xv= vvv.reshape(2,3,2)
print(xv)
print(xv.ndim)
print()
h= (xv.reshape(-1))
print(h)
print(h.ndim)

[[[ 5  6]
  [ 7  9]
  [ 4  3]]

 [[ 7  4]
  [ 9 10]
  [11 12]]]
3

[ 5  6  7  9  4  3  7  4  9 10 11 12]
1


# Broadcasting In Numpy Arrays

In [76]:
c = np.array([1,2,3])
print(c)
print(c.shape)

c1 = np.array([[1],[2],[3]])
print(c1.shape)
print(c1)
print(c + c1)

[1 2 3]
(3,)
(3, 1)
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [78]:
cv = np.array([[1],[2]])

cv1 = np.array([[1,2,3],[1,2,3]])

print(cv+cv1)

[[2 3 4]
 [3 4 5]]


#  Indexing In NumPy Arrays

In [ ]:
import numpy as np

p = np.array([1,2,3,4])

print(p[0])
print(p[-1])
print(p[::-1])

In [9]:
pp = np.array([[1,2,3],[4,5,6]])

print(pp)
print(pp[0,2])

[[1 2 3]
 [4 5 6]]
3


In [12]:
ppp= np.array([[[1,2],[6,7]]])

print(ppp)
print(ppp[0,1,1])

[[[1 2]
  [6 7]]]
7


# Slicing In NumPy Arrays

In [18]:
q = np.array([1,2,3,4,5,6])

print(q[:5])

[1 2 3 4 5]


In [19]:
qq = np.array([[1,2,3],[4,5,6]])

print(qq[1,1:2])

[5]


# Iterating Numpy Arrays

In [20]:
l = np.array([1,2,3,4])

for i in l:
    print(i)

1
2
3
4


In [21]:
l = np.array([[1,2,3,4],[1,2,3,4]])

for i in l:
    for m in i:
        print(m)

1
2
3
4
1
2
3
4


In [22]:
l = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
for i in l:
    for m in i:
        for k in m:
            print(k)

1
2
3
4
1
2
3
4
1
2
3
4


In [23]:
l = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
for i in np.nditer(l):
    print(i)

1
2
3
4
1
2
3
4
1
2
3
4


.nditer for skipping multiple for loops

In [24]:
l = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

for i,d in np.ndenumerate(l):
    print(i,d) 

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 3
(0, 2, 3) 4


.ndenumerate for knowing the value as well as the index of the value

# COPY vs VIEW

In [ ]:
K = np.array([1,2,3,4])

L = K.copy()

K[1]=4

print("ORIGINAL : ",K)
print()
print("COPY:" ,L)

In [30]:
KK = np.array([1,2,3,4])

LL = KK.view()

KK[1]=4

print("ORIGINAL : ",KK)
print()
print("VIEW:" ,LL)

ORIGINAL :  [1 4 3 4]

VIEW: [1 4 3 4]


# JOIN Array

In [32]:
f = np.array([1,2,3,4])

g = np.array([5,6,7,8])

fg = np.concatenate((f,g))
print(fg)

[1 2 3 4 5 6 7 8]


In [36]:
f = np.array([[1,2],[3,4]])
print(f)

g = np.array([[5,6],[7,8]])
print(g)
fg = np.concatenate((f,g),axis = 1)

print(fg)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


1=====row , 0=====column

In [41]:
f = np.array([1,2,3,4])

g = np.array([5,6,7,8])

fg= np.stack((f,g),axis=1)

fg1= np.hstack((f,g))#row
fg2= np.vstack((f,g))#column
fg3= np.dstack((f,g))#height

print(fg)
print()
print(fg1)
print()
print(fg2)
print()
print(fg3)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# SPLIT Array

In [43]:
o= np.array([1,2,3,4,5,6])

op = np.array_split(o,3)
print(op)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [46]:
o= np.array([[1,2],[3,4],[5,6]])
print(o)
print()
op = np.array_split(o,3,axis=1)
print(op)

[[1 2]
 [3 4]
 [5 6]]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]


# SEARCH in numpy arrays

In [48]:
b = np.array([1,2,3,4,2,76,8,2,6,2])

v= np.where(b == 2)
print(v)

(array([1, 4, 7, 9], dtype=int64),)


In [50]:
b = np.array([1,2,3,4,2,76,8,2,6,2])

v= np.where(b/2 == 1)
print(v)

(array([1, 4, 7, 9], dtype=int64),)


# Search sorted array

In [52]:
b = np.array([1,2,3,4,6,7])

v = np.searchsorted(b,5)
print(v)

4


In [54]:
b = np.array([1,2,3,4,6,7])

v = np.searchsorted(b,5,side ='right')
print(v)

4


In [56]:
b = np.array([1,2,3,4,6,7])

v = np.searchsorted(b,[5,8,9])
print(v)

[4 6 6]


# SORT array

In [57]:
b = np.array([1,5,2,34,44,0,2,3,5,89,])

v = np.sort(b)
print(v)

[ 0  1  2  2  3  5  5 34 44 89]


In [58]:
b = np.array(['f','g','e','a'])

v = np.sort(b)
print(v)

['a' 'e' 'f' 'g']


In [59]:
b = np.array([[1,5,2],[34,44,0],[2,3,5]])

v = np.sort(b)
print(v)

[[ 1  2  5]
 [ 0 34 44]
 [ 2  3  5]]


# FILTER array

In [60]:
b = np.array(['f','g','e','a'])

v = [True,False,True,False]

g = b[v]
print(g)

['f' 'e']


# Shuffle, Unique, Resize, Flatten, Ravel Functions

In [64]:
i = np.array([1,2,3,4,5])

np.random.shuffle(i)

print(i)

[3 4 5 1 2]


In [67]:
i = np.array([1,2,3,2,4,5,7,2])

l= np.unique(i,return_index = True,return_counts = True)

print(l)

(array([1, 2, 3, 4, 5, 7]), array([0, 1, 2, 4, 5, 6], dtype=int64), array([1, 3, 1, 1, 1, 1], dtype=int64))


In [70]:
i = np.array([1,2,3,4,5,6])

l = np.resize(i,(3,2))


print(l)

[[1 2]
 [3 4]
 [5 6]]


In [73]:
i = np.array([1,2,3,4,5,6])

l = np.resize(i,(3,2))

print(l)
print()
print('Flatten',l.flatten(order = 'F'))
print('Ravel',l.ravel(order = 'F'))

[[1 2]
 [3 4]
 [5 6]]

Flatten [1 3 5 2 4 6]
Ravel [1 3 5 2 4 6]


# Insert function in arrays

In [77]:
l = np.array([1,21,3,4])
print(l)
v= np.insert(l,(2,4),40)
print(v)

[ 1 21  3  4]
[ 1 21 40  3  4 40]


In [79]:
l = np.array([[1,21],[3,4]])
print(l)
v= np.insert(l,1,40,axis=1)
print(v)

[[ 1 21]
 [ 3  4]]
[[ 1 40 21]
 [ 3 40  4]]


In [81]:
l = np.array([1,21,3,4])

v= np.append(l,40)

print(v)

[ 1 21  3  4 40]


In [82]:
l = np.array([[1,21],[3,4]])

v= np.append(l,[[1,40]],axis=0)
print(v)

[[ 1 21]
 [ 3  4]
 [ 1 40]]


# Delete function in arrays

In [83]:
l = np.array([1,21,3,4])

v= np.delete(l,2)
print(v)

[ 1 21  4]


# MATRIX in NumPy Arrays

In [90]:
na = np.matrix([[1,2,3],[1,2,3]])
na1 = np.matrix([[1,2,3],[1,2,3]])

print(na+na1)
print(type(na))

[[2 4 6]
 [2 4 6]]
<class 'numpy.matrix'>


In [91]:
na = np.matrix([[1,2,3],[1,2,3]])
na1 = np.matrix([[1,2,3],[1,2,3]])

print(na-na1)
print(type(na))

[[0 0 0]
 [0 0 0]]
<class 'numpy.matrix'>


In [93]:
na = np.matrix([[1,2],[1,2]])
na1 = np.matrix([[1,2],[1,2]])

print(na*na1)
print(type(na))

[[3 6]
 [3 6]]
<class 'numpy.matrix'>


In [94]:
na = np.matrix([[1,2],[1,2]])
na1 = np.matrix([[1,2],[1,2]])

print(na.dot(na1))

[[3 6]
 [3 6]]


# MATRIX Functions in Arrays

In [98]:
tr = np.matrix([[1,2,3],[4,5,6]])

tr1 = np.transpose(tr)#1

print(tr1)
print()

print(tr.T)#2

print()

print(np.swapaxes(tr,0,1))#alternative

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


Transpose And Swapaxes

In [101]:
tr = np.matrix([[1,2],[3,4]])
print(tr)

print()

print(np.linalg.inv(tr))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


Inverse

In [103]:
tr = np.matrix([[1,2],[3,4]])
print(tr)
print()

print(np.linalg.matrix_power(tr,2))
print()

print(np.linalg.matrix_power(tr,0))
print()

print(np.linalg.matrix_power(tr,-2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



Power

In [104]:
tr = np.matrix([[1,2],[3,4]])
print(tr)
print()

print(np.linalg.det(tr))


[[1 2]
 [3 4]]

-2.0000000000000004


Determinate