# NUMPY TUTORIAL

In [2]:
import numpy as np
x = np.array([1,2,3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


how to create numpy array and checking the type

In [3]:
%timeit [j**4 for j in range(1,9)]

4.41 µs ± 42.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
import numpy as np
%timeit np.arange(1,9)**4

2.96 µs ± 136 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


checking the speed between lists and numpy

In [6]:
import numpy as np
x = [1,2,3,4]

y = np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
l =[]

for i in range(1,6):
    
    int_1 = int(input('enter the number :'))
    l.append(int_1)
    
print(np.array(l))    

enter the number :1
enter the number :2
enter the number :3
enter the number :5
enter the number :5
[1 2 3 5 5]


# Dimensions in Arrays

# 1-D Arrays --- [1,2,3,4]



#  2-D Arrays ---[ [1,2,3,4] ]

#  3-D Arrays --- [[[1,2,3,4]]]

In [10]:
ar2 = np.array([[1,2,3]])
print(ar2)
print(ar2.ndim)

[[1 2 3]]
2


n.dim ---- for checking the dimensions

In [12]:
ar3 = np.array([[[1,2,3]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]]]
3


# Arrays filled with 0's

In [14]:
import numpy as np

ar_zero = np.zeros(4)

ar_zero1 = np.zeros((3,4))

print(ar_zero1)
print()
print(ar_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0. 0. 0. 0.]


# Arrays filled with 1's

In [15]:
ar = np.ones(4)
print(ar)

[1. 1. 1. 1.]


# Create an empty array

In [17]:
ar = np.empty(4)
print(ar)

[1. 1. 1. 1.]


# An array with a range of elements

In [18]:
ar = np.arange(5)
print(ar)

[0 1 2 3 4]


# Array diagonal element filled with 1's

In [19]:
ar= np.eye(3,3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# linspace

In [20]:
ar = np.linspace(0,10,num=6)
print(ar)

[ 0.  2.  4.  6.  8. 10.]
